version: '3.8'

# Este arquivo define um ambiente de desenvolvimento completo com Nginx, PHP, MySQL e phpMyAdmin.
# Lembre-se de criar uma pasta 'src' e colocar seus arquivos PHP dentro dela.
#
# Para iniciar: docker compose up --build -d
# Para parar:   docker compose down

services:
  # --- Nginx (Servidor Web) ---
  nginx:
    image: nginx:stable-alpine
    container_name: php_app_nginx
    ports:
      # Acesse seu site em http://localhost:8000
      - "8000:80"
    volumes:
      # Mapeia a pasta 'src' do seu projeto para o container (somente leitura para o Nginx)
      - ./src:/var/www/html:ro
      # Mapeia o arquivo de configuração do Nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  # --- PHP-FPM ---
  php:
    build:
      context: . # Constrói a partir do Dockerfile na pasta atual
      dockerfile: Dockerfile
      # Adicionamos estes 'args' para passar o ID do seu usuário local para o Dockerfile.
      # Isso resolve problemas de 'Permission Denied' ao criar/escrever arquivos com o PHP.
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: php_app_php
    volumes:
      # Mapeia a pasta 'src' para que o PHP possa ler e escrever arquivos nela
      - ./src:/var/www/html:rw
    # environment:
    #   XDEBUG_MODE: develop,debug

  # --- MySQL (Banco de Dados) ---
  mysql:
    image: mysql:8.0
    container_name: php_app_mysql
    environment:
      MYSQL_ROOT_PASSWORD: phpzeiro # MUDE ESTA SENHA EM AMBIENTES REAIS!
      MYSQL_DATABASE: db_aulas
      MYSQL_USER: phpzeiro
      MYSQL_PASSWORD: secret
    ports:
      # Permite a conexão com o banco de dados a partir da sua máquina local (ex: DBeaver)
      - "3306:3306"
    volumes:
      # Garante que os dados do banco de dados persistam mesmo que o container seja removido
      - db_data:/var/lib/mysql

  # --- phpMyAdmin (Gerenciador de Banco de Dados) ---
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: php_app_pma
    links:
      - mysql:db # Cria um link para o serviço MySQL, acessível como 'db'
    environment:
      PMA_HOST: mysql # Usa o nome do serviço 'mysql' para se conectar
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: phpzeiro # Use a mesma senha root definida no serviço mysql
    ports:
      # Acesse o phpMyAdmin em http://localhost:8080
      - "8080:80"
    depends_on:
      - mysql

# --- Volumes ---
# Define o volume nomeado 'db_data' para persistir os dados do MySQL
volumes:
  db_data:

